version: "3.8"

services:
  mongo:
    image: mongo:latest
    container_name: eventease_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: saaddev13/eventease-backend:latest
    container_name: eventease_backend
    depends_on:
      - mongo
    ports:
      - "4000:4000"
    env_file:
      - ./backend/config/.env

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: saaddev13/eventease-frontend:latest
    container_name: eventease_frontend
    depends_on:
      - backend
    ports:
      - "5173:5173"
    environment:
      - VITE_BACKEND_URL=http://16.171.139.26:4000
      - VITE_API_BASE_URL=http://16.171.139.26:4000/api/v1

volumes:
  mongo-data:
